### ISSUE TITLE
Error Pause Button

### ISSUE THREAD

**Issue by KirschbaumP** [mobileappdevhm19/ILA-Flutter#76]
If the pause button is pressed the first time an error occures:
```
E/flutter ( 6216): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: ApiException 500: Exception during deserialization. (Inner exception: FormatException: Invalid date format
E/flutter ( 6216): 2019-06-12T21:34:23.4402861Z)
E/flutter ( 6216): 
E/flutter ( 6216): #0      DateTime.parse (dart:core/date_time.dart:336:7)
E/flutter ( 6216): #1      new Pause.fromJson (package:ila_swagger/model/pause.dart:28:61)
E/flutter ( 6216): #2      ApiClient._deserialize (package:ila_swagger/api_client.dart:62:22)
E/flutter ( 6216): #3      ApiClient.deserialize (package:ila_swagger/api_client.dart:109:12)
E/flutter ( 6216): #4      LecturesApi.lecturesPostPause (package:ila_swagger/api/lectures_api.dart:424:21)
E/flutter ( 6216): <asynchronous suspension>
E/flutter ( 6216): #5      _LectureViewState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:ila/views/course/lecture/lectureView.dart:70:34)
E/flutter ( 6216): <asynchronous suspension>
E/flutter ( 6216): #6      PauseButton.build.<anonymous closure> (package:ila/helpers/pauseButton.dart:20:25)
E/flutter ( 6216): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter ( 6216): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter ( 6216): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 6216): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 6216): #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
E/flutter ( 6216): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 6216): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
E/flutter ( 6216): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 6216): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6216): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6216): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6216): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 6216): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 6216): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 6216): #21     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter ( 6216): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 6216): 
E/flutter ( 6216): #0      ApiClient._deserialize (package:ila_swagger/api_client.dart:97:7)
E/flutter ( 6216): #1      ApiClient.deserialize (package:ila_swagger/api_client.dart:109:12)
E/flutter ( 6216): #2      LecturesApi.lecturesPostPause (package:ila_swagger/api/lectures_api.dart:424:21)
E/flutter ( 6216): <asynchronous suspension>
E/flutter ( 6216): #3      _LectureViewState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:ila/views/course/lecture/lectureView.dart:70:34)
E/flutter ( 6216): <asynchronous suspension>
E/flutter ( 6216): #4      PauseButton.build.<anonymous closure> (package:ila/helpers/pauseButton.dart:20:25)
E/flutter ( 6216): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter ( 6216): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter ( 6216): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 6216): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 6216): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
E/flutter ( 6216): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 6216): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
E/flutter ( 6216): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 6216): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6216): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6216): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6216): #16     _rootRunU
```

**Comment by KirschbaumP** [comment]
Server Issue. No need for changes in the App.
